package Madeline;

import Macro.DashingDirection;
import Macro.FacingDirection;
import Macro.GameMacro;
import Macro.ImageData;

final class ImageManager
{
	Madeline madeline;
	ImageManager(Madeline madeline)
	{
		this.madeline=madeline;
	}
	void imageClimbing()
	{
		if(madeline.states.climbingImageState==1)
		{
			if(madeline.states.facingDirection==FacingDirection.LEFT)
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.grabbing1Left);
				}
				else
				{
					madeline.setImage(ImageData.grabbing1LeftBlue);
				}
			}
			else
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.grabbing1Right);
				}
				else
				{
					madeline.setImage(ImageData.grabbing1RightBlue);
				}
			}
		}
		else
		{
			if(madeline.states.facingDirection==FacingDirection.LEFT)
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.grabbing2Left);
				}
				else
				{
					madeline.setImage(ImageData.grabbing2LeftBlue);
				}
			}
			else
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.grabbing2Right);
				}
				else
				{
					madeline.setImage(ImageData.grabbing2RightBlue);
				}
			}
		}
		madeline.states.climbingImageCounter+=1;
		if(madeline.states.climbingImageCounter==GameMacro.CLIMBINGIMAGECOUNTERLIMIT)
		{
			madeline.states.climbingImageCounter=0;
			if(madeline.states.climbingImageState==1)
			{
				madeline.states.climbingImageState=2;
			}
			else
			{
				madeline.states.climbingImageState=1;
			}
		}
	}
	void imageGrabbing()
	{
		if(madeline.states.facingDirection==FacingDirection.LEFT)
		{
			if(madeline.states.dashingAble==1)
			{
				madeline.setImage(ImageData.grabbing1Left);
			}
			else
			{
				madeline.setImage(ImageData.grabbing1LeftBlue);
			}
		}
		else
		{
			if(madeline.states.dashingAble==1)
			{
				madeline.setImage(ImageData.grabbing1Right);
			}
			else
			{
				madeline.setImage(ImageData.grabbing1RightBlue);
			}
		}
	}
	void imageAirborne()
	{
		if(madeline.states.facingDirection==FacingDirection.LEFT)
		{
			if(madeline.ySpeed<0)
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.jumpingLeft);
				}
				else
				{
					madeline.setImage(ImageData.jumpingLeftBlue);
				}
			}
			else if(madeline.ySpeed<=7)
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.floatingLeft);
				}
				else
				{
					madeline.setImage(ImageData.floatingLeftBlue);
				}
			}
			else
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.fallingLeft);
				}
				else
				{
					madeline.setImage(ImageData.fallingLeftBlue);
				}
			}
		}
		else
		{
			if(madeline.ySpeed<0)
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.jumpingRight);
				}
				else
				{
					madeline.setImage(ImageData.jumpingRightBlue);
				}
			}
			else if(madeline.ySpeed<=7)
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.floatingRight);
				}
				else
				{
					madeline.setImage(ImageData.floatingRightBlue);
				}
			}
			else
			{
				if(madeline.states.dashingAble==1)
				{
					madeline.setImage(ImageData.fallingRight);
				}
				else
				{
					madeline.setImage(ImageData.fallingRightBlue);
				}
			}
		}
	}
	void imageStanding()
	{
		if(madeline.states.facingDirection==FacingDirection.LEFT)
		{
			madeline.setImage(ImageData.normalLeft);
		}
		else
		{
			madeline.setImage(ImageData.normalRight);
		}
	}
	void imageDashing()
	{
		if(madeline.states.dashingDirection==DashingDirection.LEFT||madeline.states.dashingDirection==DashingDirection.LEFTDOWN||madeline.states.dashingDirection==DashingDirection.LEFTUP)
		{
			madeline.setImage(ImageData.dashingLeft);
		}
		else if(madeline.states.dashingDirection==DashingDirection.RIGHT||madeline.states.dashingDirection==DashingDirection.RIGHTDOWN||madeline.states.dashingDirection==DashingDirection.RIGHTUP)
		{
			madeline.setImage(ImageData.dashingRight);
		}
		else if(madeline.states.facingDirection==FacingDirection.LEFT)
		{
			madeline.setImage(ImageData.dashingLeft);
		}
		else
		{
			madeline.setImage(ImageData.dashingRight);
		}
	}
	void imageRunning()
	{
		if(madeline.states.runningImageState==1)
		{
			if(madeline.states.facingDirection==FacingDirection.LEFT)
			{
				madeline.setImage(ImageData.running2Left);
			}
			else
			{
				madeline.setImage(ImageData.running2Right);
			}
		}
		else if(madeline.states.runningImageState==3)
		{
			if(madeline.states.facingDirection==FacingDirection.LEFT)
			{
				madeline.setImage(ImageData.running3Left);
			}
			else
			{
				madeline.setImage(ImageData.running3Right);
			}
		}
		else
		{
			if(madeline.states.facingDirection==FacingDirection.LEFT)
			{
				madeline.setImage(ImageData.running1Left);
			}
			else
			{
				madeline.setImage(ImageData.running1Right);
			}
		}
		madeline.states.runningImageCounter+=1;
		if(madeline.states.runningImageCounter==GameMacro.RUNNINGIMAGECOUNTERLIMIT)
		{
			madeline.states.runningImageCounter=0;
			if(madeline.states.runningImageState==4)
			{
				madeline.states.runningImageState=1;
			}
			else
			{
				madeline.states.runningImageState+=1;
			}
		}
	}
}
